### ISSUE TITLE
Separate vanity hex search logic from vanity `npub`

### ISSUE THREAD

**Issue by kdmukai** [grunch/rana#15]
The hex and `npub` vanity searches are both looking at the beginning of the pubkey/`npub`.

But since the one determines the other, you can't have an arbitrary hex prefix simultaneously searching for an arbitrary `npub` prefix. For example:
```
-v 0 -n k
```
will never find a match.

So the two searches can just be pulled out into their own `if`/`else` cases without any overlapping search logic.

**Comment by diegogurpegui** [comment]
Done!
PR: https://github.com/grunch/rana/pull/16

Thanks for pointing that out
