### ISSUE TITLE
Panic when using package installed through cargo

### ISSUE THREAD

**Issue by dewey** [grunch/rana#29]
Hey, I'm trying to follow the README but I'm running into an issue when using the `--vanity` flag. When I use `--vanity-n-prefix=testing` it seems to work (`Started mining process for vanity bech32 prefix[es]:...`). I installed `rana` through via cargo.

Is this expected behaviour or am I doing something wrong?

Thanks!

```
~|⇒ rustup show
Default host: x86_64-apple-darwin
rustup home:  /Users/philipp/.rustup

stable-x86_64-apple-darwin (default)
rustc 1.67.0 (fc594f156 2023-01-24)
~|⇒ rana --version
Rana 0.5.1
~|⇒ rana --vanity=testing
thread 'main' panicked at 'The vanity prefix can only contain hexadecimal characters.', /Users/philipp/.cargo/registry/src/github.com-1ecc6299db9ec823/rana-0.5.1/src/cli.rs:138:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by grunch** [comment]
hi, --vanity is for hexadecimal only

```
$ rana --vanity dead
```

**Comment by dewey** [comment]
Ugh, I read "dead" as an example username not as the number. That's why I couldn't figure out what's the difference between "testing" and "dead" and hence the error message didn't make sense to me. Not sure if should be clarified in the README.

Thanks!
