### ISSUE TITLE
Question: estimating time to completion

### ISSUE THREAD

**Issue by rodbitkite** [grunch/rana#32]
I am mining a 7 character npub (estimated POW: 28) using all 8 cores of an Apple M1. rana has running for just under 4 days, with no results so far.

Is this within reason, or should I assume that something has gone wrong?

**Comment by grunch** [comment]
It's nothing wrong, try with a lower POW and then let it work to find pubkeys with more difficulty

**Comment by rodbitkite** [comment]
Thanks for getting back to me so quickly

I used the default difficulty which I understand to be zero. Rana reported
an estimated POW of 28 so should I have expected it to produce something by
now?

```

> rana % rana -n XXXXXXX

Started mining process for vanity bech32 prefix[es]: 'npub1["XXXXXXX"]'
(estimated pow: 28)

Benchmarking of cores disabled for vanity npub key upon proper calculation.

Mining using 8 cores...

```

**Comment by grunch** [comment]
Oh you are searching for a vanity, ok the harder is vanity the harder is going to be to find it by your CPUs

**Comment by rodbitkite** [comment]
fwiw - the vanity npub was found yesterday midday shortly after I created the issue. hopefully, this is helpful for others who are benchmarking.
