### ISSUE TITLE
Non working commands in README.md

### ISSUE THREAD

**Issue by gourcetools** [grunch/rana#36]
I've been trying theses command from the readme without succes:
`` rana --vanity-n-prefix=rana ``
I guess commands changed but not README.md

**Comment by gourcetools** [comment]
I wanted to fix it but i'm confused as my version 0.3.6 is working faster than 0.5.1. Some commands are working there and not there. Good luck frog.

**Comment by grunch** [comment]
This command works ok with last version, closing this issue

![image](https://user-images.githubusercontent.com/228364/223235234-89e7d274-ca42-4a34-aae6-385d77e07089.png)
