### ISSUE TITLE
Rana binary

### ISSUE THREAD

**Issue by DesobedienteTecnologico** [grunch/rana#40]
Hi @grunch .

I'm wondering if there is any possibility to have the binary of Rana on the releases.

I would like to have the possibility to put Rana in [DTails](https://github.com/DesobedienteTecnologico/dtails) using only final official binaries.
Due the nature of the remaster process, the system to be modified will be never connected to internet.
(It can be connected to internet, but I don't really would like to put the modified OS online in the build process for security reasons)

Thanks for your time and for giving Rana 🐸 to us.
Regards!

**Comment by grunch** [comment]
Yes of course, I can do it, if you have any suggestion on how to generate automatically those binaries on different architecture just let me know and save me a lot of time researching 😀

**Comment by DesobedienteTecnologico** [comment]
Sure! :)

I saw a project that uses Rust and they ship a binary.
Looks like **[[bin]]** under **Cargo.toml** with some other configurations does the trick:
https://github.com/wizardsardine/liana/blob/master/Cargo.toml#L12-L20


Also those seems to be interesting information to reach the goal (I'm actually not that familiar with Rust):
- https://dev.to/yjdoc2/make-a-combined-library-and-binary-project-in-rust-d4f
- https://www.programiz.com/rust/crate-and-package


Saludos!

**Comment by DesobedienteTecnologico** [comment]
Great thanks! :)

JFYI: https://github.com/cross-rs/cross
I just saw that project which is maintain by Rust developers as far I have read. You can do **cross compilation**, that will allow us to use Rana 🐸 out of the box using in Termux for example in our Android devices: [Sparrow in Android - Tutorial I made just for reference to Termux + Proot](https://estudiobitcoin.com/instala-sparrow-wallet-server-en-telefono-android/)

Also depending on the final arch, people can use it on Raspberry Pi to quite easily.
Thanks for your time with this! :)

**Comment by DesobedienteTecnologico** [comment]
> Thanks I'll be working on it

This issue can be close after this PR: 
https://github.com/grunch/rana/pull/44


Saludos! :)

**Comment by grunch** [comment]
closing it via b5e7132be591bb4b50aa414bc664d50fa4f6dcbc
