### ISSUE TITLE
Default `difficulty` issue 

### ISSUE THREAD

**Issue by akiomik** [grunch/rana#42]
In PR #41, a default value was set for the `difficulty` of `CLIArgs`, which made it impossible to specify `vanity-n-prefix` or `vanity-n-suffix` unless `--difficulty=0` is specified.

**Comment by grunch** [comment]
Oh you are right, @ok300 if you have time to give it a look would be great 😃

**Comment by ok300** [comment]
Good catch @akiomik 

@grunch I just added a PR to revert it.
